title: Góc Truyện Của Tui
email: thanhho1356@gmail.com
description: Web đọc truyện đam mỹ tuyển chọn
url: "https://trieulm-2.github.io"
baseurl: "/goctruyencuatui"
remote_theme: adamrehn/jekyll-theme-gitbook@v0.0.1
plugins: ["jekyll-remote-theme"]
markdown: kramdown