title: Góc Truyện Của Tui
email: thanhho1356@gmail.com
description: *So many books, so little time.*
url: "https://trieulm-2.github.io"
baseurl: "/goctruyencuatui"
remote_theme: pages-themes/midnight
plugins: ["jekyll-remote-theme"]
markdown: kramdown